// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface ISafeProxyFactory$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "ISafeProxyFactory";
  readonly sourceName: "contracts/interfaces/ISafeProxyFactory.sol";
  readonly abi: [{"inputs":[{"internalType":"address","name":"_singleton","type":"address"},{"internalType":"bytes","name":"data","type":"bytes"}],"name":"createProxy","outputs":[{"internalType":"address","name":"proxy","type":"address"}],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/ISafeProxyFactory.sol";
  readonly buildInfoId: "solc-0_8_26-6d0867164abde2e2c8d22e19b63bba2363140989";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["ISafeProxyFactory"]: ISafeProxyFactory$Type;
    ["contracts/interfaces/ISafeProxyFactory.sol:ISafeProxyFactory"]: ISafeProxyFactory$Type;
  }
}