// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface Enum$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "Enum";
  readonly sourceName: "contracts/interfaces/ISafe.sol";
  readonly abi: [];
  readonly bytecode: "0x6055604b600b8282823980515f1a607314603f577f4e487b71000000000000000000000000000000000000000000000000000000005f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f80fdfea2646970667358221220906873f4160cd24fe1af499c25edd2b9391e69f9ca2097502cbc0e545bdf7aa064736f6c634300081a0033";
  readonly deployedBytecode: "0x730000000000000000000000000000000000000000301460806040525f80fdfea2646970667358221220906873f4160cd24fe1af499c25edd2b9391e69f9ca2097502cbc0e545bdf7aa064736f6c634300081a0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/ISafe.sol";
  readonly buildInfoId: "solc-0_8_26-6d0867164abde2e2c8d22e19b63bba2363140989";
};

export interface ISafe$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "ISafe";
  readonly sourceName: "contracts/interfaces/ISafe.sol";
  readonly abi: [{"inputs":[{"internalType":"address","name":"to","type":"address"},{"internalType":"uint256","name":"value","type":"uint256"},{"internalType":"bytes","name":"data","type":"bytes"},{"internalType":"enum Enum.Operation","name":"operation","type":"uint8"}],"name":"execTransactionFromModule","outputs":[{"internalType":"bool","name":"success","type":"bool"}],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/ISafe.sol";
  readonly buildInfoId: "solc-0_8_26-6d0867164abde2e2c8d22e19b63bba2363140989";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["Enum"]: Enum$Type
    ["ISafe"]: ISafe$Type;
    ["contracts/interfaces/ISafe.sol:Enum"]: Enum$Type
    ["contracts/interfaces/ISafe.sol:ISafe"]: ISafe$Type;
  }
}